### ISSUE TITLE
Genjava not processing action messages

### ISSUE THREAD

**Issue by ernestmc** [rosjava/genjava#10]
Genjava ignores messages generated from action message files. Apparently this has to do with the actionlib message generator putting it's output in [this](https://github.com/ros/common_msgs/blob/jade-devel/actionlib_msgs/cmake/actionlib_msgs-extras.cmake.em#L52) location.

**Comment by jubeira** [comment]
Note: see the observations in the PR referenced above for more details about action messages generation.
